version: "3.7"

services:
  modanisa-case:
    container_name: modanisa-case
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 8080:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
